In [1]:
import random
def perceptron(x,wt):
    f=0
    for i,w in zip(x,wt):
        f+=w*i
    if f>=1:
        return 1
    else:
        return 0
x=[5,0.2]
#wt=[-1,1]
wt=random.sample(range(-1, 2), 2) 
print('Random Weights are',wt)
perceptron(x,wt)

Random Weights are [0, 1]


0

In [2]:
import random

def perceptron(x,wt):
    f=0
    for i,w in zip(x,wt):
        w=w/10
        f+=w*i
    if f>=1:
        return 1
    else:
        return 0

x=[7.8,2,2,0.5]
#wt=[1,1,0,1]
wt=random.sample(range(-1, 4), 4) 
print('Random Weights are',wt)

perceptron(x,wt)

Random Weights are [3, 1, -1, 0]


1

In [3]:
import random
def perceptron(x,wt):
    f=0
    for i,w in zip(x,wt):
        f+=w*i
    if f>=1:
        return 1
    else:
        return 0
x=[5,0.2,1]
print("x classified as =",x[2],"\n")
#wt=[1,-1]
wt=random.sample(range(-1, 2), 2) 
print('Random Weights are',wt)
cls=perceptron(x,wt)
if cls==x[2]:
    print("correctly classified")
else:
    print("Incorrectly classified")
    cls=perceptron(x,wt)


x classified as = 1 

Random Weights are [1, -1]
correctly classified


# Perceptron

In [4]:
# Make a prediction with weights
def predict(row, weights):
    activation = weights[0]
    for i in range(len(row)-1):
        activation += weights[i + 1] * row[i]
    return 1.0 if activation >= 0.0 else 0.0

# test predictions of action and horror features
dataset = [[2,2,0],
    [1,2,0],
    [5,4,1],
    [2,1,0],
    [3,3,1],
    [7,2,1],
    [5,2,1],
    [6,1,1],
    [8,-0.2,1],
    [7,3,1]]
weights = [-0.4, 0.09999999999999992, 0.10000000000000003]
for row in dataset:
    prediction = predict(row, weights)
    print("Expected=%d, Predicted=%d" % (row[-1], prediction))


Expected=0, Predicted=0
Expected=0, Predicted=0
Expected=1, Predicted=1
Expected=0, Predicted=0
Expected=1, Predicted=1
Expected=1, Predicted=1
Expected=1, Predicted=1
Expected=1, Predicted=1
Expected=1, Predicted=1
Expected=1, Predicted=1


# Extimate weights with Schocastic gradient descent

In [5]:
# Make a prediction with wt; Extimate weights with Stochastic gradient descent
def predict(row, wt):
    activation = wt[0]
    for i in range(len(row)-1):
        activation += wt[i + 1] * row[i]
    return 1.0 if activation >= 0.0 else 0.0
 
# Estimate Perceptron wt using stochastic gradient descent
def train_wt(train, l_rate, n_turn):
    wt = [0.0 for i in range(len(train[0]))]
    for turn in range(n_turn):
        sum_error = 0.0
        for row in train:
            prediction = predict(row, wt)
            error = row[-1] - prediction
            sum_error += error**2
            wt[0] = wt[0] + l_rate * error
            for i in range(len(row)-1):
                wt[i + 1] = wt[i + 1] + l_rate * error * row[i]
        print('>turn=%d, lrate=%.3f, error=%.3f' % (turn, l_rate, sum_error))
    return wt
 
# Calculate wt
dataset = [[2,2,0],
    [1,2,0],
    [5,4,1],
    [2,1,0],
    [3,3,1],
    [7,2,1],
    [5,2,1],
    [6,1,1],
    [8,-0.2,1],
    [7,3,1]]
l_rate = 0.1
n_turn = 4
wt = train_wt(dataset, l_rate, n_turn)
print(wt)
for row in dataset:
    prediction = predict(row, wt)
    print("Expected=%d, Predicted=%d" % (row[-1], prediction))


>turn=0, lrate=0.100, error=3.000
>turn=1, lrate=0.100, error=3.000
>turn=2, lrate=0.100, error=3.000
>turn=3, lrate=0.100, error=1.000
[-0.4, 0.09999999999999992, 0.10000000000000003]
Expected=0, Predicted=0
Expected=0, Predicted=0
Expected=1, Predicted=1
Expected=0, Predicted=0
Expected=1, Predicted=1
Expected=1, Predicted=1
Expected=1, Predicted=1
Expected=1, Predicted=1
Expected=1, Predicted=1
Expected=1, Predicted=1


## Feed Forward network with multiple neurons

## Objective 
### Add a hidden layers

### Use continuous activation functions (sigmoid / ReLU)

### Perform forward propagation through layers

In [1]:
# definition of sigmoidal Activation Function
import math

def sigmoid(x):
    return 1.0 / (1.0 + math.exp(-x))


In [2]:
# Evaluate the output of single unit (neuron)
def neuron_output(weights, inputs):
    activation = weights[0]  # bias
    for i in range(len(inputs)):
        activation += weights[i + 1] * inputs[i]
    return sigmoid(activation)

In [3]:
def forward_propagate(ffnet_layers, row):
    inputs = row[:-1]   # exclude label
    print('input:',row)
    for layer in ffnet_layers:
        new_inputs = []
        i = 0;
        
        for neuron in layer:
            output = neuron_output(neuron, inputs)
            new_inputs.append(output)
            
        inputs = new_inputs
    

    return inputs[0]    # final output

In [4]:
# Create a Feed Forward Network (ffnet) with one hidded layer having two neurons and outlayer with one neuron.
ffnet_layers = [
    [   # input layer to Hidden layer
        [0.1, 0.2, -0.3],   # neuron 1: bias, w1, w2
        [-0.1, 0.4, 0.1]    # neuron 2: bias, w1, w2
    ],
    [   # hidden layer to Output layer
        [0.05, 0.3, -0.2]   # bias, w_hidden1, w_hidden2
    ]
]

In [5]:
dataset = [
    [1,2,0],
    [5,4,1],
    [2,1,0],
    [3,3,1],
    [7,2,1],
    [5,2,1],
    [6,1,1],
    [8,-0.2,1],
    [7,3,1]
]

In [6]:
for row in dataset:
    output = forward_propagate(ffnet_layers, row)
    prediction = 1 if output >= 0.5 else 0
    print(f"Expected={row[-1]}, Predicted={prediction}, Output={output:.3f}")

input: [1, 2, 0]
Expected=0, Predicted=1, Output=0.513
input: [5, 4, 1]
Expected=1, Predicted=1, Output=0.503
input: [2, 1, 0]
Expected=0, Predicted=1, Output=0.519
input: [3, 3, 1]
Expected=1, Predicted=1, Output=0.506
input: [7, 2, 1]
Expected=1, Predicted=1, Output=0.518
input: [5, 2, 1]
Expected=1, Predicted=1, Output=0.515
input: [6, 1, 1]
Expected=1, Predicted=1, Output=0.521
input: [8, -0.2, 1]
Expected=1, Predicted=1, Output=0.529
input: [7, 3, 1]
Expected=1, Predicted=1, Output=0.513


## Integrate sgd based training with Feed Forward Network

In [2]:
# define acrtivation function
import math
import random

def sigmoid(x):
    return 1.0 / (1.0 + math.exp(-x))

def sigmoid_derivative(output):
    return output * (1.0 - output)

In [3]:
#initialise network parameters
def initialize_network(n_inputs, n_hidden, n_outputs):
    network = []

    hidden_layer = []
    for _ in range(n_hidden):
        neuron = {
            'weights': [random.uniform(-0.5, 0.5) for _ in range(n_inputs + 1)]
        }
        hidden_layer.append(neuron)
    network.append(hidden_layer)

    output_layer = []
    for _ in range(n_outputs):
        neuron = {
            'weights': [random.uniform(-0.5, 0.5) for _ in range(n_hidden + 1)]
        }
        output_layer.append(neuron)
    network.append(output_layer)

    return network


In [4]:
#Forward Propagation
def forward_propagate(network, row):
    inputs = row[:-1]

    for layer in network:
        new_inputs = []
        for neuron in layer:
            activation = neuron['weights'][0]  # bias
            for i in range(len(inputs)):
                activation += neuron['weights'][i + 1] * inputs[i]
            neuron['output'] = sigmoid(activation)
            new_inputs.append(neuron['output'])
        inputs = new_inputs

    return inputs

In [5]:
#Backward Propagation
def backward_propagate_error(network, expected):
    for i in reversed(range(len(network))):
        layer = network[i]
        errors = []

        if i == len(network) - 1:  # output layer
            for j, neuron in enumerate(layer):
                errors.append(expected[j] - neuron['output'])
        else:  # hidden layer
            for j in range(len(layer)):
                error = 0.0
                for neuron in network[i + 1]:
                    error += neuron['weights'][j + 1] * neuron['delta']
                errors.append(error)

        for j, neuron in enumerate(layer):
            neuron['delta'] = errors[j] * sigmoid_derivative(neuron['output'])

In [6]:
# weight updation with sgd
def update_weights(network, row, l_rate):
    inputs = row[:-1]

    for i, layer in enumerate(network):
        if i != 0:
            inputs = [neuron['output'] for neuron in network[i - 1]]

        for neuron in layer:
            neuron['weights'][0] += l_rate * neuron['delta']  # bias
            for j in range(len(inputs)):
                neuron['weights'][j + 1] += l_rate * neuron['delta'] * inputs[j]

In [7]:
#Training with sgd
def train_network(network, train, l_rate, n_epoch):
    for epoch in range(n_epoch):
        sum_error = 0.0
        for row in train:
            outputs = forward_propagate(network, row)
            expected = [row[-1]]
            sum_error += (expected[0] - outputs[0]) ** 2
            backward_propagate_error(network, expected)
            update_weights(network, row, l_rate)
        print(f"Epoch={epoch}, Error={sum_error:.4f}")

In [8]:
def predict(network, row):
    output = forward_propagate(network, row)[0]
    return 1 if output >= 0.5 else 0

In [9]:
#dataset
dataset = [
    [1,2,0],
    [5,4,1],
    [2,1,0],
    [3,3,1],
    [7,2,1],
    [5,2,1],
    [6,1,1],
    [8,-0.2,1],
    [7,3,1]
]

network = initialize_network(2, 2, 1)

train_network(network, dataset, l_rate=0.3, n_epoch=15)

for row in dataset:
    output = forward_propagate(network, row)[0]
    prediction = predict(network, row)
    print(f"Expected={row[-1]}, Output={output:.3f}, Predicted={prediction}")

Epoch=0, Error=1.6567
Epoch=1, Error=1.5959
Epoch=2, Error=1.5595
Epoch=3, Error=1.5367
Epoch=4, Error=1.5214
Epoch=5, Error=1.5106
Epoch=6, Error=1.5024
Epoch=7, Error=1.4958
Epoch=8, Error=1.4902
Epoch=9, Error=1.4851
Epoch=10, Error=1.4804
Epoch=11, Error=1.4760
Epoch=12, Error=1.4716
Epoch=13, Error=1.4673
Epoch=14, Error=1.4629
Expected=0, Output=0.741, Predicted=1
Expected=1, Output=0.787, Predicted=1
Expected=0, Output=0.767, Predicted=1
Expected=1, Output=0.768, Predicted=1
Expected=1, Output=0.802, Predicted=1
Expected=1, Output=0.793, Predicted=1
Expected=1, Output=0.800, Predicted=1
Expected=1, Output=0.805, Predicted=1
Expected=1, Output=0.800, Predicted=1


# Multi Layer Neural Network with Keras with SGD and optimizer

In [19]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from sklearn.model_selection import train_test_split

In [20]:
dataset = np.array([
    [2, 2, 0],
    [1, 2, 0],
    [5, 4, 1],
    [2, 1, 0],
    [3, 3, 1],
    [7, 2, 1],
    [5, 2, 1],
    [6, 1, 1],
    [8, -0.2, 1],
    [7, 3, 1]
], dtype=float)

X = dataset[:, :-1]   # inputs
y = dataset[:, -1]    # labels


In [21]:
# Train-test split FIRST
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [22]:
# Feedforward Neural Network
model = Sequential([
    Dense(2, activation='sigmoid', input_shape=(2,)),
    Dense(1, activation='sigmoid')
])

In [23]:
model.compile(
    optimizer=SGD(learning_rate=0.3),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


In [24]:
# Training 
history = model.fit(X_train, y_train, epochs=500, verbose=0)
 


In [25]:
# Evaluate
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print("Test Accuracy:", accuracy)

Test Accuracy: 1.0


In [26]:
# Predictions
pred = (model.predict(X_test) > 0.5).astype(int)
for i in range(len(X_test)):
    print(f"Expected={int(y_test[i])}, Predicted={pred[i][0]}")

Expected=1, Predicted=1
Expected=0, Predicted=0


# IoT Dataset (Binary Classification)

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout
from tensorflow.keras.optimizers import Adam


In [ ]:
# Load dataset using pandas

data = pd.read_csv("iot_dataset.csv")

# Assume last column is label
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values   # 0 = Normal, 1 = Attack

# Feature scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Reshape for CNN (samples, features, channels)
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test  = X_test.reshape(X_test.shape[0],  X_test.shape[1],  1)


In [ ]:
model = Sequential()

# 1st Convolution Layer
model.add(Conv1D(filters=32,
                 kernel_size=3,
                 activation='relu',
                 input_shape=(X_train.shape[1], 1)))

model.add(MaxPooling1D(pool_size=2))

# 2nd Convolution Layer
model.add(Conv1D(filters=64,
                 kernel_size=3,
                 activation='relu'))

model.add(MaxPooling1D(pool_size=2))

# Flatten
model.add(Flatten())

# Fully Connected Layer
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))

# Output Layer
model.add(Dense(1, activation='sigmoid'))


In [ ]:
model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)


In [ ]:
history = model.fit(
    X_train, y_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)


In [17]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)


ValueError: in user code:

    C:\Users\Suresh\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1323 test_function  *
        return step_function(self, iterator)
    C:\Users\Suresh\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1314 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Suresh\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Suresh\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Suresh\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Suresh\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1307 run_step  **
        outputs = model.test_step(data)
    C:\Users\Suresh\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\training.py:1266 test_step
        y_pred = self(x, training=False)
    C:\Users\Suresh\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\base_layer.py:1013 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\Suresh\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\keras\engine\input_spec.py:251 assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer sequential is incompatible with the layer: expected axis -1 of input shape to have value 2 but received input with shape (None, 2, 1)


# Image Classification

In [34]:
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import load_img, img_to_array

# Load image
img = load_img("100.jpg", target_size=(64, 64))  # RGB by default
img_array = img_to_array(img)
# Add batch dimension
img_array = np.expand_dims(img_array, axis=0)

print("Input shape to CNN:", img_array.shape)

print("Image shape:", img_array.shape)

Input shape to CNN: (1, 64, 64, 3)
Image shape: (1, 64, 64, 3)


In [35]:
print(img_array)

[[[[196. 185. 181.]
   [190. 179. 175.]
   [190. 176. 173.]
   ...
   [ 43.  30.  21.]
   [ 48.  31.  21.]
   [ 47.  32.  27.]]

  [[193. 182. 178.]
   [189. 178. 174.]
   [195. 181. 178.]
   ...
   [ 46.  31.  26.]
   [ 54.  37.  30.]
   [ 59.  35.  35.]]

  [[190. 179. 175.]
   [191. 180. 176.]
   [194. 180. 177.]
   ...
   [ 89.  86.  71.]
   [ 52.  47.  28.]
   [ 42.  24.  12.]]

  ...

  [[154. 140. 131.]
   [176. 161. 156.]
   [182. 168. 159.]
   ...
   [ 72.  56.  40.]
   [ 82.  66.  53.]
   [ 73.  65.  46.]]

  [[174. 155. 140.]
   [161. 145. 132.]
   [177. 163. 150.]
   ...
   [ 74.  53.  36.]
   [ 75.  57.  43.]
   [ 81.  63.  51.]]

  [[182. 166. 153.]
   [176. 157. 142.]
   [167. 150. 134.]
   ...
   [ 70.  55.  36.]
   [ 72.  54.  44.]
   [ 84.  66.  54.]]]]


In [36]:
img_array = img_array / 255.0

In [37]:
print(img_array)

[[[[0.76862746 0.7254902  0.70980394]
   [0.74509805 0.7019608  0.6862745 ]
   [0.74509805 0.6901961  0.6784314 ]
   ...
   [0.16862746 0.11764706 0.08235294]
   [0.1882353  0.12156863 0.08235294]
   [0.18431373 0.1254902  0.10588235]]

  [[0.75686276 0.7137255  0.69803923]
   [0.7411765  0.69803923 0.68235296]
   [0.7647059  0.70980394 0.69803923]
   ...
   [0.18039216 0.12156863 0.10196079]
   [0.21176471 0.14509805 0.11764706]
   [0.23137255 0.13725491 0.13725491]]

  [[0.74509805 0.7019608  0.6862745 ]
   [0.7490196  0.7058824  0.6901961 ]
   [0.7607843  0.7058824  0.69411767]
   ...
   [0.34901962 0.3372549  0.2784314 ]
   [0.20392157 0.18431373 0.10980392]
   [0.16470589 0.09411765 0.04705882]]

  ...

  [[0.6039216  0.54901963 0.5137255 ]
   [0.6901961  0.6313726  0.6117647 ]
   [0.7137255  0.65882355 0.62352943]
   ...
   [0.28235295 0.21960784 0.15686275]
   [0.32156864 0.25882354 0.20784314]
   [0.28627452 0.25490198 0.18039216]]

  [[0.68235296 0.60784316 0.54901963]
   [0.6

In [42]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

model = Sequential()

model.add(Conv2D(
    filters=8,
    kernel_size=(3,3),
    activation='relu',
    input_shape=(64,64,3)
))

model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(16, (3,3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
model.add(Dense(32, activation='relu'))
output=model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model.summary()


Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_8 (Conv2D)            (None, 62, 62, 8)         224       
_________________________________________________________________
max_pooling2d_8 (MaxPooling2 (None, 31, 31, 8)         0         
_________________________________________________________________
conv2d_9 (Conv2D)            (None, 29, 29, 16)        1168      
_________________________________________________________________
max_pooling2d_9 (MaxPooling2 (None, 14, 14, 16)        0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 3136)              0         
_________________________________________________________________
dense_8 (Dense)              (None, 32)                100384    
_________________________________________________________________
dense_9 (Dense)              (None, 1)                

In [39]:
print(model.output)

KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), name='dense_7/Sigmoid:0', description="created by layer 'dense_7'")


In [40]:
prediction = model.predict(img_array)


In [41]:
if prediction[0][0] > 0.5:
    print("Prediction: DOG")
else:
    print("Prediction: CAT")


Prediction: DOG
